version: '3'

services:
  users-db:
    container_name: users-db
    build: https://gitlab.com:${DYSFN_TOKEN}@gitlab.com/dysfn/flask-microservices-users.git#master:project/db
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0
  users-service:
    container_name: users-service
    build: https://gitlab.com:${DYSFN_TOKEN}@gitlab.com/dysfn/flask-microservices-users.git
    command: gunicorn -b 0.0.0.0:5000 manage:app
    expose:
      - '5000'
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
    depends_on:
      - users-db
    links:
      - users-db
  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      - users-service
    links:
      - users-service
